### ISSUE TITLE
[Question]: What orientation algorithm for Neon ?

### ISSUE THREAD

**Issue by christian-nils** [pupil-labs/pl-rec-export#1]
Hello,

First of all, I have to thank you for providing your customers with this repo. This is a game changer for us as we don't need to rely on Pupil-labs Cloud to extract meaningful data (it simplifies our data processing pipelines).

A quick question related to the Neon orientation estimation. I see that this data is directly extracted from the data compared to the Invisible eye-tracker. But I am curious to know, what is the fusion sensor used for the Neon, is this something you could share? It is mentioned "fusion engine" in the docs (https://docs.pupil-labs.com/neon/how-tos/data-collection-with-the-companion-app/calibrate-the-imu-for-accurate-yaw-orientation/) but no more details related to the actual algorithm used.

Thanks in advance

**Comment by mikelgg93** [comment]
Hi @christian-nils ! 
You can find more information about the IMU sensor and how they are fused here https://invensense.tdk.com/products/motion-tracking/9-axis/icm-20948/

**Comment by christian-nils** [comment]
Hi!

Thanks for your quick reply. So if I understand well you get the orientation directly from TDK's MotionFusion algorithm with the DMP feature of the IMU?

Thanks again for the quick reply
