### ISSUE TITLE
IMU Timestamp inconsistency, bug?

### ISSUE THREAD

**Issue by christian-nils** [pupil-labs/pl-rec-export#2]
Hi,

I have some inconsistency in the IMU timestamp vector when extracting the data. (I actually see the same issue with the extracted IMU data from the Cloud platform). If I plot the timestamps against their corresponding indices, I have the following:

![image](https://github.com/pupil-labs/pl-rec-export/assets/2658014/8a4bb713-b233-417e-a26b-ff5958a97500)

Looking at the min and max value, I get: 

```python
pl_imu_data["timestamp [ns]"].max()
1.7508000326489248e+19
pl_imu_data["timestamp [ns]"].min()
1.952867219604081e+16
```

I am not sure where the problem come from, is it the collected data that are corrupted? or is it the extraction tool?

_Edit_: I did check the other time vectors (the *.time files) and they all look fine.

**Comment by JackCaster** [comment]
I have the same issue. Any news on this by any chance?

**Comment by mikelgg93** [comment]
This has been addressed via a Companion App update. Do you still experience this issue in recordings made with version 2.7.4?

**Comment by JackCaster** [comment]
> This has been addressed via a Companion App update. Do you still experience this issue in recordings made with version 2.7.4?

It looks like this issue was fixed with the last update. Thanks!
